addpath("data\")
addpath("data\maps\")
addpath("data\test_cases\")
addpath("data\models\")

addpath("simulation\")
addpath("simulation\utils\")
addpath("simulation\scripts\")
addpath("simulation\config\")

addpath("src\")
addpath("src\algorithm\")
addpath("src\algorithm\classes\")
addpath("src\algorithm\utils\")
addpath("src\algorithm\utils\mex\")

addpath("src\cosim\")
addpath("src\cosim\classes\")
addpath("src\cosim\utils\")
addpath("src\cosim\utils\mex\")
addpath("src\cosim\scripts\")

addpath("src\dependencies\")
addpath("src\dependencies\utils\")
addpath("src\dependencies\utils\mex\")
addpath("src\dependencies\classes\")
addpath("src\dependencies\scripts\")

addpath("src\trailer-MEI\")
addpath("src\trailer-MEI\classes\")
addpath("src\trailer-MEI\scripts\")
addpath("src\trailer-MEI\utils\")
addpath("src\trailer-MEI\utils\mex\")

addpath("assets\")
addpath("assets\img\")
addpath("assets\gif\")
addpath("assets\info\")

addpath(".")