
%% 初始化推演场景
% 获取当前位置推演用的地图
new_edgeID_dist = genEdgeID_dist(ego.edgeID,ego.lanePosition,resolution);
if isKey(simRoadNetwork_dict,new_edgeID_dist)
    edgeID_dist = new_edgeID_dist;
else
    disp('当前位置没有记录新的推演地图，别担心哒，仍然使用上一个推演地图哦')
end

% 生成推演场景
s = SimScenario('net',simRoadNetwork_dict{edgeID_dist});

% 获取当前对象跟踪器映射
vehKeys = objTracking_dict.keys;

% 添加自车和他车到场景
egoState = convertVehState(new_entity_dict,lane_from_connection_dict, ...
           lane_to_connection_dict,s,ego);

s = s.addVehicle(Vehicle4COMPASS( ...
    'delta',params.rushness_dict(ego.vClass), ...
    'a_max',ego.sumo_params.accel, ...
    'b_comf',ego.sumo_params.decel, ...
    's_min',ego.sumo_params.minGap, ...
    'T_hw',ego.sumo_params.tau, ...
    'max_spd',ego.sumo_params.maxSpeed, ...
    'speed_factor',ego.sumo_params.speedFactor,...
    'lc_speed_gain',ego.sumo_params.lcSpeedGain,...
    'lc_speed_gain_right',ego.sumo_params.lcSpeedGainRight,...
    'route',ego.route, ...
    'routeIdx',ego.routeIdx, ...
    'routeNum',length(ego.route), ...
    'edgeID',ego.edgeID, ...
    'laneID',ego.laneID, ...
    'L',ego.length, ...
    'W',ego.width, ...
    'color',ego.sumo_params.color, ...
    'id',ego.vehID ...
    ),egoState);


for i = 1:length(vehKeys)
    vehKey = vehKeys{i};
    % 下面进行判断车辆是否在仿真路网内部
    vehNo = objTracking_dict(vehKey);
    if s.net.isInNet(vehicleDummies{vehNo}.edgeID)
        vehState = convertVehState(new_entity_dict,lane_from_connection_dict, ...
                   lane_to_connection_dict,s,vehicleDummies{vehNo});
 
        s = s.addVehicle(Vehicle4COMPASS( ...
            'delta',params.rushness_dict(vehicleDummies{vehNo}.vClass), ...
            'a_max',vehicleDummies{vehNo}.sumo_params.accel, ...
            'b_comf',vehicleDummies{vehNo}.sumo_params.decel, ...
            's_min',vehicleDummies{vehNo}.sumo_params.minGap, ...
            'T_hw',vehicleDummies{vehNo}.sumo_params.tau, ...
            'max_spd',vehicleDummies{vehNo}.sumo_params.maxSpeed, ...
            'speed_factor',vehicleDummies{vehNo}.sumo_params.speedFactor,...
            'lc_speed_gain',vehicleDummies{vehNo}.sumo_params.lcSpeedGain,...
            'lc_speed_gain_right',vehicleDummies{vehNo}.sumo_params.lcSpeedGainRight,...
            'route',vehicleDummies{vehNo}.route,...
            'routeIdx',vehicleDummies{vehNo}.routeIdx,...
            'edgeID',vehicleDummies{vehNo}.edgeID,...
            'laneID',vehicleDummies{vehNo}.laneID, ...
            'routeNum',length(vehicleDummies{vehNo}.route), ...
            'v_des',vehicleDummies{vehNo}.v_des,...
            'L',vehicleDummies{vehNo}.length,...
            'W',vehicleDummies{vehNo}.width,...
            'color',vehicleDummies{vehNo}.vehicle.PlotColor, ...
            'id',vehicleDummies{vehNo}.vehID...
            ),vehState);
    end

end


if ~isempty(theScene)
    s.lastRouteInfo = route; % 保存一下上次的决策记录
    s.lastDecisionTimeGap = lastDecisionTimeGap; % 上次决策距离本次决策的时间差
end

% 推演场景初始化
s = s.initSenario();